$color = rgba(0, 0, 0, 1.0)
$inner_color = rgba(0, 0, 0, 0.90)
$outer_color = rgba(185, 30, 47, 0.65)
$font_color = rgba(232, 232, 232, 1.0)
$placeholder_color = rgba(133, 133, 133, 0.92)
$check_color = rgba(192, 192, 192, 1.0)
